"""Build downloadable executive reports from delivery analysis results."""


SEVERITY_PRIORITY = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}


def _text(value, default: str = "Not provided") -> str:
    """Return readable single-line text for Markdown output."""
    if value is None:
        return default
    cleaned = " ".join(str(value).split())
    return cleaned or default


def _ordered(findings: list | None) -> list[dict]:
    """Return findings in stable severity order, ignoring invalid entries."""
    valid = [item for item in (findings or []) if isinstance(item, dict)]
    return sorted(
        enumerate(valid),
        key=lambda item: (
            SEVERITY_PRIORITY.get(_text(item[1].get("severity"), "Low").title(), 4),
            item[0],
        ),
    )


def _render_finding_section(findings: list | None, limit: int, severities: set[str] | None = None) -> list[str]:
    rendered = []
    for _, finding in _ordered(findings):
        severity = _text(finding.get("severity"), "Low").title()
        if severities and severity not in severities:
            continue
        rendered.extend([
            f"- **Severity:** {severity}",
            f"  - **Finding:** {_text(finding.get('finding'))}",
            f"  - **Evidence:** {_text(finding.get('evidence'))}",
            f"  - **Recommended action:** {_text(finding.get('recommended_action'))}",
        ])
        if sum(line.startswith("- **Severity:") for line in rendered) >= limit:
            break
    return rendered or ["No findings identified."]


def build_markdown_report(
    scoring_result: dict,
    executive_summary: dict,
    risk_findings: list,
    dependency_findings: list,
    governance_findings: list,
    recommendations: list,
) -> str:
    """Return a complete evidence-backed executive report in Markdown."""
    scoring_result = scoring_result if isinstance(scoring_result, dict) else {}
    executive_summary = executive_summary if isinstance(executive_summary, dict) else {}

    lines = [
        "# Delivery Chief of Staff Executive Report",
        "",
        "Generated by Delivery Chief of Staff.",
        "",
        "## Executive Summary",
        "",
        _text(executive_summary.get("headline")),
        "",
        _text(executive_summary.get("summary")),
        "",
        f"**Decision required:** {_text(executive_summary.get('decision_required'))}",
        "",
        "## Delivery Health Score",
        "",
        f"Delivery Health Score: {_text(scoring_result.get('score'), 'N/A')}/100",
        "",
        f"Status: {_text(scoring_result.get('status'), 'Unknown')}",
        "",
        f"Summary: {_text(scoring_result.get('status_summary'))}",
        "",
        "## Leadership Attention Required",
        "",
    ]

    leadership_attention = executive_summary.get("leadership_attention")
    if isinstance(leadership_attention, list) and leadership_attention:
        lines.extend(f"- {_text(action)}" for action in leadership_attention)
    else:
        lines.append("No immediate leadership actions were identified.")

    lines.extend(["", "## Top Risks", ""])
    lines.extend(_render_finding_section(risk_findings, 5, {"Critical", "High"}))

    lines.extend(["", "## Dependency and Blocker Findings", ""])
    lines.extend(_render_finding_section(dependency_findings, 5))

    lines.extend(["", "## Governance Findings", ""])
    lines.extend(_render_finding_section(governance_findings, 5))

    lines.extend(["", "## Recommended Actions", ""])
    valid_recommendations = [item for item in (recommendations or []) if isinstance(item, dict)]
    if valid_recommendations:
        for recommendation in valid_recommendations[:7]:
            lines.extend([
                f"- **Severity:** {_text(recommendation.get('severity'), 'Low').title()}",
                f"  - **Source:** {_text(recommendation.get('source'))}",
                f"  - **Evidence key:** {_text(recommendation.get('evidence_key'))}",
                f"  - **Recommended action:** {_text(recommendation.get('recommended_action'))}",
            ])
    else:
        lines.append("No recommended actions were generated.")

    lines.extend(["", "## Score Deductions", ""])
    deductions = scoring_result.get("deductions")
    valid_deductions = [item for item in deductions if isinstance(item, dict)] if isinstance(deductions, list) else []
    if valid_deductions:
        for deduction in valid_deductions:
            lines.extend([
                f"- **Severity:** {_text(deduction.get('severity'), 'Low').title()}",
                f"  - **Category group:** {_text(deduction.get('category_group'))}",
                f"  - **Points:** {_text(deduction.get('points'), '0')}",
                f"  - **Reason:** {_text(deduction.get('reason'))}",
                f"  - **Evidence key:** {_text(deduction.get('evidence_key'))}",
            ])
    else:
        lines.append("No score deductions were applied.")

    lines.extend(["", "## Category Deduction Totals", ""])
    category_totals = scoring_result.get("category_totals")
    if isinstance(category_totals, dict) and category_totals:
        for category, points in category_totals.items():
            lines.append(f"- **{_text(category)}:** {_text(points, '0')} points")
    else:
        lines.append("No category deductions were recorded.")

    lines.extend(["", "## Capped Categories", ""])
    capped_categories = scoring_result.get("capped_categories")
    if isinstance(capped_categories, list) and capped_categories:
        lines.extend(f"- {_text(category)}" for category in capped_categories)
    else:
        lines.append("No category caps were reached.")

    lines.extend(["", "## Evidence and Audit Trail", ""])
    all_findings = list(risk_findings or []) + list(dependency_findings or []) + list(governance_findings or [])
    valid_findings = [item for item in all_findings if isinstance(item, dict)]
    if valid_findings:
        for finding in valid_findings:
            lines.extend([
                f"- **Source:** {_text(finding.get('source'))}",
                f"  - **Evidence key:** {_text(finding.get('evidence_key'))}",
                f"  - **Severity:** {_text(finding.get('severity'), 'Low').title()}",
                f"  - **Category:** {_text(finding.get('category'))}",
                f"  - **Category group:** {_text(finding.get('category_group'))}",
                f"  - **Finding:** {_text(finding.get('finding'))}",
                f"  - **Evidence:** {_text(finding.get('evidence'))}",
                f"  - **Recommended action:** {_text(finding.get('recommended_action'))}",
            ])
    else:
        lines.append("No evidence findings were generated.")

    return "\n".join(lines).rstrip() + "\n"
